name: Auto deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository == 'Luis-Valenzuela-Concha/WikInf'
    steps:
      - name: Deploy last changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            export PATH=~/.local/share/pnpm:$PATH
            source ~/.nvm/nvm.sh
            cd ~/WikInf
            git pull
            pnpm install
            pm2 stop wikinf > /dev/null 2>&1
            if git diff --name-only HEAD~1 HEAD | grep "_meta.json"; then
              echo "_meta.json files changed, running extra script..."
              if [ -d ".next"]; then
                rm -rf .next
                echo "Next.js build folder deleted."
              fi
            fi
            pnpm build
            pm2 start wikinf > /dev/null 2>&1
